"""migration

Revision ID: 119a5e440863
Revises: 533ee36a6856
Create Date: 2022-06-08 14:06:19.411050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119a5e440863'
down_revision = '533ee36a6856'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
