"""migration1

Revision ID: 2246d165cc22
Revises: af9cc24b1479
Create Date: 2022-06-08 13:36:09.947829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2246d165cc22'
down_revision = 'af9cc24b1479'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
