"""migration1

Revision ID: 533ee36a6856
Revises: 7a3b4e5a5b2f
Create Date: 2022-06-08 13:58:12.424243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533ee36a6856'
down_revision = '7a3b4e5a5b2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
