"""migration1

Revision ID: 7a3b4e5a5b2f
Revises: 2246d165cc22
Create Date: 2022-06-08 13:36:22.088551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3b4e5a5b2f'
down_revision = '2246d165cc22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
