"""migration

Revision ID: af9cc24b1479
Revises: 4c188d75312a
Create Date: 2022-06-08 11:48:19.273619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9cc24b1479'
down_revision = '4c188d75312a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
